swagger: '2.0'
info:
    title: RecipeBlog
    version: 1.0.0
    description: This is a blog for recipes
paths:
    /recipes:
        get:
            tags:
                - recipes
            responses:
                '200':
                    description: Returns a list of recipes
                    schema:
                        type: array
                        items:
                            type: string
                    examples: {}
            summary: Get all the recipes in API
            description: Returns all recipes that are registered in API
        post:
            tags:
                - recipes
            parameters:
                -
                    name: body
                    description: The recipe to be created.
                    schema:
                        $ref: '#/definitions/New-Recipe'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when recipe is successfully added to the database.
                    schema:
                        $ref: '#/definitions/New-Recipe'
                '400':
                    description: Missing some parameter. Title and content are required.
                    schema:
                        $ref: '#/definitions/Error'
            summary: Create a new recipe into the app
            description: Creates a new recipe instance with its required details for further usage.
    '/recipes/{RecipeID}':
        get:
            tags:
                - recipes
            parameters:
                -
                    name: RecipeID
                    description: ID of <recipe>
                    in: path
                    required: true
                    type: string
            responses:
                '200':
                    description: Returns all details of the given recipe.
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json:
                            RecipeID: 5fa725fd-cec3-11f0-b43f-901b0eec5991
                            Title: TestRecipe
                            Content: For testing
                            createdAt: '2025-12-01T16:37:08.000Z'
                            updatedAt: '2025-12-01T16:37:08.000Z'
                '404':
                    description: Returns error when recipe not found.
                    schema:
                        $ref: '#/definitions/Error'
            operationId: RecipeID
            summary: Get full detail of a recipe
            description: Will return all details of a given recipe based on RecipeID given.
        put:
            tags:
                - recipes
            parameters:
                -
                    name: body
                    description: |
                        Contains new data to be changed in the specified Recipe
                    schema:
                        $ref: '#/definitions/New-Recipe'
                    in: body
                    required: true
            responses:
                '201':
                    description: Returns 201 upon successsful modification of film
                    schema:
                        $ref: '#/definitions/New-Recipe'
                    examples:
                        application/json:
                            -
                                Title: '0'
                                Content: abc
                                Image: im2gf
                '400':
                    description: Returns 400 when one or multile required parameters are missing
                    schema:
                        $ref: '#/definitions/Error'
                    examples:
                        application/json:
                            -
                                error: 'cannot change info, because some parameters are missing'
                '404':
                    description: Returns 404 when Recipe to be modified is not found by the given RecipeID
                    schema:
                        $ref: '#/definitions/Error'
                    examples:
                        application/json:
                            -
                                error: Film not found
        delete:
            tags:
                - recipes
            responses:
                '204':
                    description: Returns "No Content" when removal of recipes is successful
                    schema:
                        $ref: '#/definitions/Error'
                    examples:
                        application/json:
                            -
                                error: No countent
                '404':
                    description: 'Returns error, when recipe with specified ID does not exist'
                    schema:
                        $ref: '#/definitions/Error'
                    examples:
                        application/json:
                            -
                                error: Not found
            summary: Delete a recipe from the app
            description: |
                Deletes an entry from the app
        parameters:
            -
                name: RecipeID
                description: |
                    ID of recipe
                in: path
                required: true
                type: string
    '/challenges/{ChallengeID}':
        get:
            tags:
                - challenges
            responses:
                '200':
                    description: Returns all details of a given challenge
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        application/json: |-
                            {
                                "ChalleneID": "43ad65a0-d4f7-11h0-b43r-901b0eec5891",
                                "Title": "TestTitle",
                                "Descrpition": "TestDescription",
                                "Is_Active" : "Yes"
                                "createdAt": "2025-12-01T16:37:08.000Z",
                                "updatedAt": "2025-12-01T16:37:08.000Z"
                            }
                '404':
                    description: Returns error when challenge not found
                    schema:
                        $ref: '#/definitions/Error'
            operationId: ChallengeID
            summary: Get full detail of a challenge
            description: Will return all details of a given challenge based on ChallengeID given
        parameters:
            -
                name: ChallengeID
                description: ID of challenge
                in: path
                required: true
                type: string
    /users:
        get:
            tags:
                - users
            responses:
                '200':
                    description: Returns a list of users
                    schema:
                        type: array
                        items:
                            type: string
            summary: Get all the users in API
            description: Returns all users that are registered in API
        post:
            tags:
                - users
            parameters:
                -
                    name: body
                    schema:
                        $ref: '#/definitions/New-User'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when User is successfully added to the DB
                    schema:
                        $ref: '#/definitions/New-User'
                    examples: {}
                '400':
                    description: 'Send 400, when the request body is missing some parameter.'
                    schema:
                        $ref: '#/definitions/Error'
                    examples:
                        application/json:
                            -
                                error: Missin some parameter.
            summary: Add a new User to the app
            description: Enables user signup functions and further usage.
    /challenges:
        get:
            tags:
                - challenges
            responses:
                '200':
                    description: Returns a list of challenges
                    schema:
                        type: array
                        items:
                            type: string
            summary: Get all the challenges in API
        post:
            tags:
                - challenges
            parameters:
                -
                    name: body
                    description: The challenge to be created
                    schema:
                        $ref: '#/definitions/New-Challenge'
                    in: body
                    required: true
            responses:
                '201':
                    description: Send 201 when challenge is successfully added to the database
                    schema:
                        $ref: '#/definitions/New-Challenge'
                '400':
                    description: Missing some parameter. Title and content are required.
                    schema:
                        $ref: '#/definitions/Error'
            summary: Create a new challenge into the app
            description: Creates a new challenge with its required details for further usage.
definitions:
    Error:
        title: Root Type for Error
        description: ''
        type: object
        properties:
            error:
                type: string
        example:
            error: Error message
    New-Recipe:
        title: Root Type for New-Recipe
        description: ''
        required:
            - Content
            - Title
        type: object
        properties:
            Title:
                type: string
            Content:
                type: string
            Image:
                type: string
        example:
            Title: NewRecipeTitle
            Content: NewRecipeContent
            Image: NewRecipeImage
    Delete-Recipe:
        title: Root Type for Delete-Recipe
        description: ''
        type: object
        properties:
            RecipeID:
                type: string
        example:
            RecipeID: a17e59b1-9391-460a-97de-591a9cb9066d
    New-User:
        description: 'New user data, PhoneNumber2FA is optional'
        type: object
        example:
            EmailAddress: a@b.com
            Password: abc123
            UserName: tester
            PhoneNumber2FA: '1234567'
    New-Challenge:
        title: Root Type for New-Challenge
        description: ''
        type: object
        properties:
            ChallengeID:
                type: string
            Title:
                type: string
            Descrpition:
                type: string
            Is_Active:
                type: string
            createdAt:
                format: date-time
                type: string
            updatedAt:
                format: date-time
                type: string
        example:
            ChallengeID: 43ad65a0-d4f7-11h0-b43r-901b0eec5891
            Title: TestTitle
            Descrpition: TestDescription
            Is_Active: 'True'
            createdAt: '2025-12-01T16:37:08.000Z'
            updatedAt: '2025-12-01T16:37:08.000Z'
